module epfm_da_mod
!------------------------------------------------------------------------------
! EPFM data assimilation for ALBM
!
! State updated:
!   - m_waterTemp(:)  [lake water temperature profile]
!
! Parameters updated:
!   - sa_params(Param_Feta)
!   - sa_params(Param_Hscale)
!   - sa_params(Param_Dscale)
!
! Observations assimilated:
!   - daily LWST
!   - occasional Secchi depth
!
! Notes:
! 1) This module assumes the forecast/prior particles for the current
!    assimilation time have already been generated by ALBM.
! 2) For the parameter-MCMC step, you provide a callback that reruns one
!    particle over the last assimilation window with proposed parameters.
! 3) The default Secchi operator uses Secchi ~ 1.7 / Kd, with
!       Kd = feta * kext_base
!    Replace this if you already diagnose Secchi from ALBM optics.
!------------------------------------------------------------------------------

   use shr_kind_mod,       only : r8
   use shr_typedef_mod,    only : EPFM_Obs, SimTime
   use shr_param_mod,      only : NPARAM, sa_params
   use shr_param_mod,      only : Param_Feta, Param_Hscale, Param_Dscale
   use shr_ctrl_mod,       only : NPART, WATER_LAYER, masterproc
   use data_buffer_mod,    only : m_waterTemp 
   use math_utilities_mod, only : gaussian_random_generator
   use math_utilities_mod, only : ClipArray, ReflectToBounds, Randn
   use read_data_mod,      only : ReadObservations4DA
   use thermal_mod,        only : EnforceThermalConsistency 
   use mpi

   implicit none
   private
   public :: EPFM_Config
   public :: EPFM_Particle
   public :: EPFM_Initialize, EPFM_Finalize
   public :: EPFM_Assimilate
   public :: EPFM_SystematicResample
   public :: UpdateEPFMConfig
   public :: GatherParticlesToRoot, ScatterParticlesFromRoot 
   public :: ArraysToEPFMParticles, EPFMParticlesToArrays
   public :: CopyLakeStateToEPFM, SaveEPFMToLakeState 
   public :: PerturbPositiveParameter
   public :: DefaultObsOperator
   public :: epfm_cfg, epfm_obs4da

   real(r8), parameter :: PI_R8 = 3.14159265358979323846_r8
   real(r8), parameter :: TINY_R8 = 1.0e-12_r8

   type :: EPFM_Config
      real(r8) :: rho_c = 0.70_r8         ! crossover probability
      real(r8) :: rho_m = 0.10_r8         ! mutation probability
      real(r8) :: psi   = 0.01_r8         ! mutation variance multiplier (should be tuned)
      real(r8) :: sigma_lwst = 0.50_r8    ! K
      real(r8) :: sigma_log_secchi = 0.20_r8
      real(r8) :: sigma_deep = 0.1_r8     ! K
      real(r8) :: corr_len = 5._r8        ! m
      real(r8) :: temp_min = 273.15_r8    ! K
      real(r8) :: temp_max = 313.15_r8    ! K
      real(r8) :: feta_bounds(2)   = (/ 0.10_r8, 10.00_r8 /)
      real(r8) :: hscale_bounds(2) = (/ 0.50_r8, 2.00_r8 /)
      real(r8) :: dscale_bounds(2) = (/ 0.10_r8, 10.00_r8 /)
      real(r8) :: feta_log_sd   = 0.15_r8  ! log-space RW std
      real(r8) :: hscale_log_sd = 0.10_r8
      real(r8) :: dscale_log_sd = 0.15_r8
      real(r8) :: kext_base = 0.50_r8           ! baseline extinction for Secchi operator
   end type

   type :: EPFM_Particle
      real(r8), allocatable :: tw(:)       ! current prior / analysis water temp
      real(r8), allocatable :: tw_prev(:)  ! previous analysis state; used in rerun callback
      real(r8), allocatable :: params(:)   ! local sensitive parameter vector
      real(r8) :: sim_lwst   = 0.0_r8
      real(r8) :: sim_secchi = 0.0_r8
      real(r8) :: loglik     = 0.0_r8
      real(r8) :: weight     = 0.0_r8
   end type

   abstract interface
      subroutine obs_operator_ifc(tw, params, sim_lwst, sim_secchi)
         import :: r8
         implicit none
         real(r8), intent(in)  :: tw(:)
         real(r8), intent(in)  :: params(:)
         real(r8), intent(out) :: sim_lwst
         real(r8), intent(out) :: sim_secchi
      end subroutine

      subroutine rerun_window_ifc(tw_prev, params, tw_new, sim_lwst, sim_secchi)
         import :: r8
         implicit none
         real(r8), intent(in)  :: tw_prev(:)
         real(r8), intent(in)  :: params(:)
         real(r8), intent(out) :: tw_new(:)
         real(r8), intent(out) :: sim_lwst
         real(r8), intent(out) :: sim_secchi
      end subroutine
   end interface

   ! local variables
   integer, allocatable :: mcmc_parent_idx(:)
   integer, allocatable :: mcmc_mut_idx(:)

   real(r8), allocatable :: cdf(:)  ! CDF of particle weights
   real(r8), allocatable :: mcmc_mu(:)
   real(r8), allocatable :: mcmc_varx(:)
   real(r8), allocatable :: mcmc_proposal(:)
   real(r8), allocatable :: mcmc_prior(:)
   
   real(r8), allocatable :: local_temp(:,:)       ! (nz, nlocal)
   real(r8), allocatable :: local_temp_prev(:,:)  ! (nz, nlocal)
   real(r8), allocatable :: local_params(:,:)     ! (NPARAM, nlocal)

   real(r8), allocatable :: global_temp(:,:)       ! (nz, npart)
   real(r8), allocatable :: global_temp_prev(:,:)  ! (nz, npart)
   real(r8), allocatable :: global_params(:,:)     ! (NPARAM, npart)

   type(EPFM_Particle), allocatable :: particles(:)
   type(EPFM_Particle), allocatable :: particles_old(:)
   type(EPFM_Particle), allocatable :: offspring(:)

   type(EPFM_Obs), allocatable :: epfm_obs4da(:)
   type(EPFM_Config) :: epfm_cfg

contains

!==============================================================================
! Public driver
!==============================================================================
   subroutine EPFM_Initialize(lakeId, time)
      integer, intent(in) :: lakeId
      type(SimTime), intent(in) :: time
      ! local variables
      integer :: ii, nparent, nmut

      allocate(local_temp(WATER_LAYER+1,1))
      allocate(local_temp_prev(WATER_LAYER+1,1))
      allocate(local_params(NPARAM,1))
      if (masterproc) then
         nparent = max(2, int(epfm_cfg%rho_c * real(NPART, r8)))
         nmut = max(1, int(epfm_cfg%rho_m * real(NPART, r8)))

         allocate(cdf(NPART))
         allocate(mcmc_parent_idx(nparent))
         allocate(mcmc_mut_idx(nmut))
         allocate(mcmc_mu(WATER_LAYER+1))
         allocate(mcmc_varx(WATER_LAYER+1))
         allocate(mcmc_proposal(WATER_LAYER+1))
         allocate(mcmc_prior(WATER_LAYER+1))
         allocate(global_temp(WATER_LAYER+1,NPART))
         allocate(global_temp_prev(WATER_LAYER+1,NPART))
         allocate(global_params(NPARAM,NPART))
         allocate(particles(NPART))
         allocate(particles_old(NPART))
         allocate(offspring(NPART))
         do ii = 1, NPART, 1
            allocate(particles(ii)%tw(WATER_LAYER+1))
            allocate(particles(ii)%tw_prev(WATER_LAYER+1))
            allocate(particles(ii)%params(NPARAM))
            allocate(particles_old(ii)%tw(WATER_LAYER+1))
            allocate(particles_old(ii)%tw_prev(WATER_LAYER+1))
            allocate(particles_old(ii)%params(NPARAM))
            allocate(offspring(ii)%tw(WATER_LAYER+1))
            allocate(offspring(ii)%tw_prev(WATER_LAYER+1))
            allocate(offspring(ii)%params(NPARAM))
         end do
      end if
      ! read observations
      call ReadObservations4DA(lakeId, time, epfm_obs4da)
   end subroutine

   subroutine EPFM_Finalize()
      
      deallocate(local_temp)
      deallocate(local_temp_prev)
      deallocate(local_params)
      if (masterproc) then
         deallocate(cdf)
         deallocate(mcmc_parent_idx)
         deallocate(mcmc_mut_idx)
         deallocate(mcmc_mu)
         deallocate(mcmc_varx)
         deallocate(mcmc_proposal)
         deallocate(mcmc_prior)
         deallocate(global_temp)
         deallocate(global_temp_prev)
         deallocate(global_params)
         deallocate(particles)
         deallocate(particles_old)
         deallocate(offspring)
      end if
      deallocate(epfm_obs4da)
   end subroutine

   !------------------------------------------------------------------------------
   !
   ! Purpose: These subroutines are used to data transfer and communications.
   !
   !------------------------------------------------------------------------------
   subroutine GatherParticlesToRoot(rank)
      integer, intent(in) :: rank
      integer :: ierr, ierr_abort
      integer :: nz, nlocal, npara
      
      nz = size(local_temp, 1)
      nlocal = size(local_temp, 2)
      npara = size(local_params, 1)
      
      call MPI_Gather(local_temp, nz*nlocal, MPI_REAL8, &
         global_temp, nz*nlocal, MPI_REAL8, 0, MPI_COMM_WORLD, ierr)
      if (ierr /= MPI_SUCCESS) then
         write(*,*) "MPI_Gather local_temp failed on rank ", rank
         call MPI_Abort(MPI_COMM_WORLD, ierr, ierr_abort)
      end if

      call MPI_Gather(local_temp_prev, nz*nlocal, MPI_REAL8, &
         global_temp_prev, nz*nlocal, MPI_REAL8, 0, MPI_COMM_WORLD, ierr)
      if (ierr /= MPI_SUCCESS) then
         write(*,*) "MPI_Gather local_temp_prev failed on rank ", rank
         call MPI_Abort(MPI_COMM_WORLD, ierr, ierr_abort)
      end if

      call MPI_Gather(local_params, npara*nlocal, MPI_REAL8, &
         global_params, npara*nlocal, MPI_REAL8, 0, MPI_COMM_WORLD, ierr)
      if (ierr /= MPI_SUCCESS) then
         write(*,*) "MPI_Gather local_params failed on rank ", rank
         call MPI_Abort(MPI_COMM_WORLD, ierr, ierr_abort)
      end if
   end subroutine

   subroutine ScatterParticlesFromRoot(rank)
      integer, intent(in) :: rank
      integer :: ierr, ierr_abort
      integer :: nz, nlocal, npara

      nz = size(local_temp, 1)
      nlocal = size(local_temp, 2)
      npara = size(local_params, 1)

      call MPI_Scatter(global_temp, nz*nlocal, MPI_REAL8, &
         local_temp, nz*nlocal, MPI_REAL8, 0, MPI_COMM_WORLD, ierr)
      if (ierr /= MPI_SUCCESS) then
         write(*,*) "MPI_Scatter local_temp failed on rank ", rank
         call MPI_Abort(MPI_COMM_WORLD, ierr, ierr_abort)
      end if

      call MPI_Scatter(global_temp_prev, nz*nlocal, MPI_REAL8, &
         local_temp_prev, nz*nlocal, MPI_REAL8, 0, MPI_COMM_WORLD, ierr)
      if (ierr /= MPI_SUCCESS) then
         write(*,*) "MPI_Scatter local_temp_prev failed on rank ", rank
         call MPI_Abort(MPI_COMM_WORLD, ierr, ierr_abort)
      end if

      call MPI_Scatter(global_params, npara*nlocal, MPI_REAL8, &
         local_params, npara*nlocal, MPI_REAL8, 0, MPI_COMM_WORLD, ierr)
      if (ierr /= MPI_SUCCESS) then
         write(*,*) "MPI_Scatter local_params failed on rank ", rank
         call MPI_Abort(MPI_COMM_WORLD, ierr, ierr_abort)
      end if
   end subroutine

   subroutine ArraysToEPFMParticles()
      integer :: ii

      do ii = 1, NPART, 1
         particles(ii)%tw        = global_temp(:,ii)
         particles(ii)%tw_prev   = global_temp_prev(:,ii)
         particles(ii)%params    = global_params(:,ii)
      end do
   end subroutine

   subroutine EPFMParticlesToArrays()
      integer :: ii

      do ii = 1, NPART, 1
         global_temp(:,ii)       = particles(ii)%tw
         global_temp_prev(:,ii)  = particles(ii)%tw_prev
         global_params(:,ii)     = particles(ii)%params
      end do
   end subroutine 

   subroutine CopyLakeStateToEPFM(update_prev)
      logical, intent(in) :: update_prev

      if (update_prev) then
         local_temp_prev = local_temp
      end if
      local_temp(:,1) = m_waterTemp
      local_params(:,1) = sa_params
   end subroutine

   subroutine SaveEPFMToLakeState()

      m_waterTemp = local_temp(:,1)
      sa_params = local_params(:,1)
      call EnforceThermalConsistency()
   end subroutine

   subroutine UpdateEPFMConfig(kext_base)
      real(r8), intent(in) :: kext_base

      epfm_cfg%kext_base = kext_base
   end subroutine

   !------------------------------------------------------------------------------
   !
   ! Purpose: The main subroutine for the workflow of data assimilation.
   !
   !------------------------------------------------------------------------------
   subroutine EPFM_Assimilate(obs, obs_operator, rerun_window)
      type(EPFM_Obs), intent(in)    :: obs
      procedure(obs_operator_ifc)   :: obs_operator
      procedure(rerun_window_ifc)   :: rerun_window
      ! local variables
      integer :: ii
      logical :: has_obs

      has_obs = obs%has_lwst .or. obs%has_secchi
      if (.not. has_obs) then
         do ii = 1, NPART, 1
            particles(ii)%weight = 1.0_r8 / real(NPART, r8)
         end do
         return
      end if

      ! 1) Evaluate prior likelihoods and weights
      do ii = 1, NPART, 1
         call obs_operator(particles(ii)%tw, particles(ii)%params, &
                           particles(ii)%sim_lwst, particles(ii)%sim_secchi)
         particles(ii)%loglik = LogLikelihood(obs, epfm_cfg, &
            particles(ii)%sim_lwst, particles(ii)%sim_secchi)
      end do
      call NormalizeLogWeights(particles)

      ! 2) EPFM GA-MCMC refinement of the state (m_waterTemp)
      call GA_MCMC_StateRefine(epfm_cfg, obs, obs_operator)

      ! 3) Resample (may consider conditional resampling)
      call EPFM_SystematicResample()

      ! 4) MCMC parameter update after resampling
      !call ParameterMCMC(epfm_cfg, obs, rerun_window)

      ! 5) Set equal weights after analysis
      do ii = 1, NPART, 1
         particles(ii)%weight = 1.0_r8 / real(NPART, r8)
      end do

   end subroutine

!==============================================================================
! Default observation utilities
!==============================================================================

   real(r8) function LogLikelihood(obs, cfg, sim_lwst, sim_secchi) result(ll)
      type(EPFM_Obs)   , intent(in) :: obs
      type(EPFM_Config), intent(in) :: cfg
      real(r8), intent(in) :: sim_lwst, sim_secchi
      real(r8) :: z

      ll = 0.0_r8

      if (obs%has_lwst) then
         z  = (obs%lwst - sim_lwst) / max(cfg%sigma_lwst, TINY_R8)
         ll = ll - 0.5_r8 * z * z
      end if

      if (obs%has_secchi) then
         z  = (log(max(obs%secchi, 1.0e-6_r8)) - log(max(sim_secchi, &
            1.0e-6_r8))) / max(cfg%sigma_log_secchi, TINY_R8)
         ll = ll - 0.5_r8 * z * z
      end if
   end function

   subroutine DefaultObsOperator(tw, params, sim_lwst, sim_secchi)
      real(r8), intent(in)  :: tw(:)
      real(r8), intent(in)  :: params(:)
      real(r8), intent(out) :: sim_lwst
      real(r8), intent(out) :: sim_secchi
      real(r8) :: kd

      sim_lwst = tw(1)
      kd = max(1.0e-6_r8, epfm_cfg%kext_base * params(Param_Feta))
      sim_secchi = 1.7_r8 / kd
   end subroutine

!==============================================================================
! Weight handling
!==============================================================================

   subroutine NormalizeLogWeights(particles_in)
      type(EPFM_Particle) , intent(inout) :: particles_in(:)
      integer :: ii, nn
      real(r8) :: lmax, s

      nn = size(particles_in)
      lmax = particles_in(1)%loglik
      do ii = 2, nn, 1
         lmax = max(lmax, particles_in(ii)%loglik)
      end do

      s = 0.0_r8
      do ii = 1, nn, 1
         particles_in(ii)%weight = exp(particles_in(ii)%loglik - lmax)
         s = s + particles_in(ii)%weight
      end do

      s = max(s, TINY_R8)
      do ii = 1, nn, 1
         particles_in(ii)%weight = particles_in(ii)%weight / s
      end do
   end subroutine

!==============================================================================
! GA-MCMC state refinement (EPFM importance-sampling refinement)
!==============================================================================

   subroutine GA_MCMC_StateRefine(cfg, obs, obs_operator)
      type(EPFM_Config), intent(in) :: cfg
      type(EPFM_Obs), intent(in)    :: obs
      procedure(obs_operator_ifc)   :: obs_operator
      ! local variables
      integer :: nn, nz, nsel, nmut 
      integer :: ii, ip1, ip2, imut, k
      real(r8) :: xi, alpha_log, u
      real(r8) :: sim_lwst_p, sim_secchi_p
      real(r8) :: logq_new, logq_old, loglik_p

      nn  = size(particles)
      nz = size(mcmc_mu)
      nsel = size(mcmc_parent_idx)
      nmut = size(mcmc_mut_idx)

      do ii = 1, nn, 1
         offspring(ii)%tw      = particles(ii)%tw
         offspring(ii)%tw_prev = particles(ii)%tw_prev
         offspring(ii)%params  = particles(ii)%params
         offspring(ii)%weight  = particles(ii)%weight
         offspring(ii)%loglik  = particles(ii)%loglik
      end do

      call WeightedMomentsState(particles, mcmc_mu, mcmc_varx)

      ! Roulette-wheel selection pool for crossover
      call RouletteSelection(particles, nsel, mcmc_parent_idx)

      if (mod(nsel,2) /= 0) then
         mcmc_parent_idx(nsel) = mcmc_parent_idx(1)
      end if

      do ii = 1, nsel, 2
         ip1 = mcmc_parent_idx(ii)
         ip2 = mcmc_parent_idx(ii+1)
         call random_number(xi)

         offspring(ip1)%tw = xi * particles(ip1)%tw + (1.0_r8 - xi) * &
            particles(ip2)%tw
         offspring(ip2)%tw = (1.0_r8 - xi) * particles(ip1)%tw + xi * &
            particles(ip2)%tw

         call ClipArray(offspring(ip1)%tw, cfg%temp_min, cfg%temp_max)
         call ClipArray(offspring(ip2)%tw, cfg%temp_min, cfg%temp_max)
      end do

      ! Mutation of random offspring particles
      call RandomUniqueIndex(nn, nmut, mcmc_mut_idx)
      do ii = 1, nmut, 1
         imut = mcmc_mut_idx(ii)
         call MutateState(offspring(imut)%tw, mcmc_varx, cfg%psi, &
                  cfg%temp_min, cfg%temp_max)
      end do

      ! MCMC accept/reject against current prior particles
      do ii = 1, nn, 1
         mcmc_proposal = offspring(ii)%tw
         mcmc_prior    = particles(ii)%tw

         call obs_operator(mcmc_proposal, particles(ii)%params, &
               sim_lwst_p, sim_secchi_p)
         loglik_p = LogLikelihood(obs, cfg, sim_lwst_p, sim_secchi_p)

         ! prior distribution
         logq_new = LogIndependentGaussian(mcmc_proposal, mcmc_mu, mcmc_varx)
         logq_old = LogIndependentGaussian(mcmc_prior, mcmc_mu, mcmc_varx)

         alpha_log = (loglik_p + logq_new) - (particles(ii)%loglik + logq_old)
         call random_number(u)

         if (log(u) <= min(0.0_r8, alpha_log)) then
            particles(ii)%tw         = mcmc_proposal
            particles(ii)%sim_lwst   = sim_lwst_p
            particles(ii)%sim_secchi = sim_secchi_p
            particles(ii)%loglik     = loglik_p
         end if
      end do

      call NormalizeLogWeights(particles)
   end subroutine

   subroutine WeightedMomentsState(particles_in, mu, varx)
      type(EPFM_Particle), intent(in)  :: particles_in(:)
      real(r8), intent(out) :: mu(:), varx(:)
      integer :: ii, kk, nn, nz
      real(r8) :: w

      nn  = size(particles_in)
      nz = size(mu)

      mu   = 0.0_r8
      varx = 0.0_r8

      do ii = 1, nn, 1
         w = particles_in(ii)%weight
         do kk = 1, nz, 1
            mu(kk) = mu(kk) + w * particles_in(ii)%tw(kk)
         end do
      end do

      do ii = 1, nn, 1
         w = particles(ii)%weight
         do kk = 1, nz, 1
            varx(kk) = varx(kk) + w * (particles_in(ii)%tw(kk) - mu(kk))**2
         end do
      end do

      where (varx < 1.0e-8_r8) varx = 1.0e-8_r8
   end subroutine

   real(r8) function LogIndependentGaussian(x, mu, varx) result(val)
      real(r8), intent(in) :: x(:)     ! sample
      real(r8), intent(in) :: mu(:)    ! expectation
      real(r8), intent(in) :: varx(:)  ! variance
      integer :: ii, nx

      nx = size(x)
      val = 0.0_r8
      do ii = 1, nx, 1
         val = val - 0.5_r8 * ( (x(ii)-mu(ii))**2 / max(varx(ii),TINY_R8) + &
            log(2._r8*PI_R8*max(varx(ii),TINY_R8)) )
      end do
   end function

   subroutine MutateState(tw, varx, psi, tmin, tmax)
      real(r8), intent(inout) :: tw(:)
      real(r8), intent(in)    :: varx(:)
      real(r8), intent(in)    :: psi, tmin, tmax
      integer :: k, nz
      real(r8) :: eta

      nz = size(tw)
      call random_number(eta)
      k = 1 + INT(DBLE(nz) * eta)
      k = min(max(k,1), nz)

      tw(k) = tw(k) + Randn() * sqrt(max(psi*varx(k), 1.0e-10_r8))
      tw(k) = min(max(tw(k), tmin), tmax)
   end subroutine

!==============================================================================
! Resampling
!==============================================================================

   subroutine EPFM_SystematicResample()
      integer :: nn, ii, jj
      real(r8) :: u0, u

      nn = size(particles)
      do ii = 1, nn
         particles_old(ii)%tw         = particles(ii)%tw
         particles_old(ii)%tw_prev    = particles(ii)%tw_prev
         particles_old(ii)%params     = particles(ii)%params
         particles_old(ii)%sim_lwst   = particles(ii)%sim_lwst
         particles_old(ii)%sim_secchi = particles(ii)%sim_secchi
         particles_old(ii)%loglik     = particles(ii)%loglik
         particles_old(ii)%weight     = particles(ii)%weight
      end do

      cdf(1) = particles_old(1)%weight
      do ii = 2, nn
         cdf(ii) = cdf(ii-1) + particles_old(ii)%weight
      end do
      cdf(nn) = 1.0_r8

      call random_number(u0)
      u0 = u0 / real(nn, r8)

      jj = 1
      do ii = 1, nn
         u = u0 + real(ii-1, r8) / real(nn, r8)
         do while (u > cdf(jj) .and. jj < nn)
            jj = jj + 1
         end do
         particles(ii)%tw         = particles_old(jj)%tw
         particles(ii)%tw_prev    = particles_old(jj)%tw_prev
         particles(ii)%params     = particles_old(jj)%params
         particles(ii)%sim_lwst   = particles_old(jj)%sim_lwst
         particles(ii)%sim_secchi = particles_old(jj)%sim_secchi
         particles(ii)%loglik     = particles_old(jj)%loglik
         particles(ii)%weight     = 1.0_r8 / real(nn, r8)
      end do
   end subroutine

!==============================================================================
! Parameter MCMC after resampling
!==============================================================================
   real(r8) function PerturbPositiveParameter(base_value, log_sd, &
         lower_bound, upper_bound) result(value_p)
      real(r8), intent(in) :: base_value
      real(r8), intent(in) :: log_sd
      real(r8), intent(in) :: lower_bound
      real(r8), intent(in) :: upper_bound
      ! local variables
      real(r8) :: rand

      call gaussian_random_generator(0._r8, sqrt(0.2_r8), rand)
      value_p = base_value * exp(log_sd * rand)
      value_p = ReflectToBounds(value_p, lower_bound, upper_bound)
   end function

   subroutine ParameterMCMC(cfg, obs, rerun_window)
      type(EPFM_Config), intent(in) :: cfg
      type(EPFM_Obs), intent(in)    :: obs
      procedure(rerun_window_ifc)   :: rerun_window
      ! local variables
      integer :: ii, nz
      real(r8) :: params_p(NPARAM)
      real(r8) :: tw_new(WATER_LAYER+1)
      real(r8) :: sim_lwst_p, sim_secchi_p, loglik_p
      real(r8) :: base_value, alpha_log, u

      nz = size(tw_new)

      do ii = 1, size(particles)
         params_p = particles(ii)%params

         base_value = particles(ii)%params(Param_Feta)
         params_p(Param_Feta) = PerturbPositiveParameter(base_value, &
            cfg%feta_log_sd, cfg%feta_bounds(1), cfg%feta_bounds(2))

         base_value = particles(ii)%params(Param_Hscale)
         params_p(Param_Hscale) = PerturbPositiveParameter(base_value, &
            cfg%hscale_log_sd, cfg%hscale_bounds(1), cfg%hscale_bounds(2))

         base_value = particles(ii)%params(Param_Dscale)
         params_p(Param_Dscale) = PerturbPositiveParameter(base_value, &
            cfg%dscale_log_sd, cfg%dscale_bounds(1), cfg%dscale_bounds(2))

         call rerun_window(particles(ii)%tw_prev, params_p, tw_new, &
                           sim_lwst_p, sim_secchi_p)
         loglik_p = LogLikelihood(obs, cfg, sim_lwst_p, sim_secchi_p)

         alpha_log = loglik_p - particles(ii)%loglik 
         call random_number(u)

         if (log(u) <= min(0.0_r8, alpha_log)) then
            particles(ii)%params     = params_p
            particles(ii)%tw         = tw_new
            particles(ii)%sim_lwst   = sim_lwst_p
            particles(ii)%sim_secchi = sim_secchi_p
            particles(ii)%loglik     = loglik_p
         end if
      end do
   end subroutine

!==============================================================================
! Helpers
!==============================================================================

   subroutine RouletteSelection(particles_in, nsel, idx)
      type(EPFM_Particle), intent(in)  :: particles_in(:)
      integer, intent(in)  :: nsel
      integer, intent(out) :: idx(nsel)
      ! local variables
      integer :: ii, jj, nn
      real(r8) :: u

      nn = size(particles_in)
      cdf(1) = particles_in(1)%weight
      do ii = 2, nn, 1
         cdf(ii) = cdf(ii-1) + particles_in(ii)%weight
      end do
      cdf(nn) = 1.0_r8

      do jj = 1, nsel, 1
         call random_number(u)
         idx(jj) = nn - COUNT(u<=cdf) + 1
      end do
   end subroutine

   subroutine RandomUniqueIndex(nn, mm, idx)
      integer, intent(in)  :: nn
      integer, intent(in)  :: mm
      integer, intent(out) :: idx(mm)
      ! local variables
      integer :: ii, kk
      real(r8) :: u
      logical :: used(nn)

      used = .false.
      do ii = 1, mm, 1
         do
            call random_number(u)
            kk = 1 + int(u * real(nn, r8))
            kk = min(max(kk,1), nn)
            if (.not. used(kk)) exit
         end do
         used(kk) = .true.
         idx(ii) = kk
      end do
   end subroutine

end module epfm_da_mod
