#!/bin/bash -l

#PBS -l nodes=5:ppn=20
#PBS -l walltime=04:00:00
#PBS -q standby 
#PBS -N isimip 
#PBS -m e
#PBS -j oe

module unload netcdf/4.5.0
module unload impi/2017.1.132

cd $PBS_O_WORKDIR
export NETCDF_HOME=/home/tan80/packages/Pnetcdf_openmpi_2.1.6
export LD_LIBRARY_PATH=$NETCDF_HOME/lib:$LD_LIBRARY_PATH
module load intel/17.0.1.132 openmpi/2.1.6

export MV2_USE_SHMEM_COLL=0

NPROCS=`wc -l < $PBS_NODEFILE`

mpirun -np $NPROCS ALBM namelist.bLake
